/**
 * Created by erik on 09.07.2017.
 */


/**
 * Counts the occurrences  of the subString in string
 * @param {String} string the string to check
 * @param {String} subString the subString to find
 *
 * @see http://stackoverflow.com/questions/4009756/how-to-count-string-occurrence-in-string/7924240#7924240
 */
function countOccurrences(string, subString) {
    let n = 0;
    let pos = 0;
    let step =  subString.length;

    while (pos <= string.length) {
        pos = string.indexOf(subString, pos);
        if (pos >= 0) {
            n = n + 1;
            pos += step;
        } else break;
    }
    return n;
}


module.exports = {
    /**
     * Gets a String of input and converts it to html by the rules of markdown
     * @param {String} string
     * @returns {String}
     */
    applyMarkdown:function (string) {
        let ausgabe = '';
        /*let lines = string.split(/\n/);
        for(let i = 0; i < lines.length; i++){

        }*/
        //Find the heading that are marked with #
        string = string.replace(/#{1,6}[^\n]*/g, function (matched){
            const headingType = countOccurrences(/#{1,6}/.exec(matched)[0], '#');
            return matched.replace(/#{1,6}([^\n])*#*^/g, '<h' + headingType + '>$1</h'+ headingType + '>');
        });
        string = string.replace(/(^|\n)([-*] ?){3,}/g, '$1<hr />');

        return string;
    },

    /**
     * Removes every Character not allowed in HTML and replaces it with the HTML code for it
     * @param {String} string The user input to replace
     * @returns {String}
     */
    removeHTML:function (string) {
        return string.replace(/&/g, '&amp;').replace(/</g, '&lt;');
    },

    /**
     * Replaces every line break with an <br />
     * @param {String} string The user input to replace
     * @returns {String}
     */
    addLineBreaks:function (string) {//TODO remove this in codeBlocks generated by applyMarkdown
        return string.replace(/\n/, '<br />\n');
    }
};